import Link from 'next/link'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import './globals.css'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My React CRUD Example',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  return (
    <html>
      <body>
        <div className='navbar'>
          <Link href='/' className='logo'>taehykim</Link>
          <Link href='/list'>List</Link>
          <Link href='/write'>Write</Link>
          {
            session
              ? <span>{ session.user.name }<LogoutBtn/></span>
              : <span><LoginBtn/></span>
          }
        </div>
        {children}
      </body>
    </html>
  )
}
